name: check for breaking changes
description: GitHub Action that check the current branch for any breaking change commits based on the commit message.
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  commit-base-ref:
    required: false
    description: Commit range to exclude from check
    default: $GITHUB_BASE_REF
  commit-head-ref:
    required: false
    description: Commit range to include in check
    default: $GITHUB_HEAD_REF
  commit-msg-pattern:
    required: false
    description: Pattern used to check
    default: 'BREAKING:\|BREAKING CHANGE:\|BREAKING CHANGES:'
outputs:
  contains-breaking-changes:
    description: Indicates whether or not the action found any breaking changes in the commit range.
    value: ${{ steps.check.outputs.contains-breaking }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.checkout-repo == 'true'
      with:
        fetch-depth: 0

    - name: Check for breaking changes
      id: check
      shell: bash
      env:
        COMMIT_BASE_REF: ${{ inputs.commit-base-ref }}
        COMMIT_HEAD_REF: ${{ inputs.commit-head-ref }}
        COMMIT_MSG_PATTERN: ${{ inputs.commit-msg-pattern }}
      run: |
        commits=$(git log origin/"$COMMIT_BASE_REF"..origin/"$COMMIT_HEAD_REF")

        if echo "$commits" | grep -q "$COMMIT_MSG_PATTERN"; then
          echo "contains-breaking=true" >> "$GITHUB_OUTPUT"
        else
          echo "contains-breaking=false" >> "$GITHUB_OUTPUT"
        fi
