name: terraform Lint
description: Lints terraform repository
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  terraform-cli-credentials-token:
    required: true
    description: The terraform cli config credentials token
  terraform-cli-config-file:
    required: false
    description: Relative or absolute path to the terraform cli config file
    default: ./.terraformrc
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - name: Create credentials file if missing
      id: create-credentials-file
      uses: open-turo/actions-tf/auth@v3
      with:
        terraform-cli-credentials-token: ${{ inputs.terraform-cli-credentials-token }}
        terraform-cli-config-file: ${{ inputs.terraform-cli-config-file }}
    - name: Setup tools
      # Provide opportunity to install terraform, golang, and others
      uses: open-turo/action-setup-tools@v1
    - name: Pre-commit
      uses: open-turo/action-pre-commit@v1
    - name: Post run
      if: always() && ${{ steps.create-credentials-file.outputs.terraform-cli-config-file-created }}
      shell: bash
      run: rm "$HOME/${{ inputs.terraform-cli-config-file }}" || true
