name: terraform Lint
description: GitHub Action that lints a Terraform based repository via [action-pre-commit](https://github.com/open-turo/action-pre-commit)
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  terraform-cli-credentials-token:
    required: true
    description: The terraform cli config credentials token
  terraform-cli-config-file:
    required: false
    description: Relative path to the terraform cli config file
    default: .terraformrc
  s3-bucket-name:
    required: false
    description: S3 bucket name to cache dependencies to speed up runs.
  s3-bucket-region:
    required: false
    description: S3 bucket region to cache dependencies to speed up runs.
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.checkout-repo == 'true'
      with:
        # Use fetch-depth of zero to obtain all commit history so that commit message linting can
        # be properly performed.
        fetch-depth: 0
    - name: Create credentials file if missing
      id: create-credentials-file
      uses: open-turo/actions-tf/auth@v3
      with:
        terraform-cli-credentials-token: ${{ inputs.terraform-cli-credentials-token }}
        terraform-cli-config-file: ${{ inputs.terraform-cli-config-file }}
    - name: Setup tools
      # Provide opportunity to install terraform, golang, and others
      uses: open-turo/action-setup-tools@v3

    - name: Configure Terraform plugin cache
      shell: bash
      run: |
        echo "TF_PLUGIN_CACHE_DIR=${{ runner.temp }}/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
        mkdir --parents "${{ runner.temp }}/.terraform.d/plugin-cache"
    - name: Compute terraform plugin cache key
      if: inputs.s3-bucket-name != ''
      id: tf_plugin_cache_key
      run: |
        echo "key=terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl', '**/terraform.tf', '**/versions.tf') }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Load cached terraform plugins if available
      if: inputs.s3-bucket-name != ''
      uses: everpcpc/actions-cache@v2
      id: read_cache
      with:
        bucket: ${{ inputs.s3-bucket-name }}
        use-fallback: false
        path: ${{ runner.temp }}/.terraform.d/plugin-cache
        key: ${{ env.cache-name }}-${{ steps.tf_plugin_cache_key.outputs.key }}
        restore-keys: ${{ env.cache-name }}-
      env:
        AWS_REGION: ${{ inputs.s3-bucket-region }}
        cache-name: ${{ github.event.repository.name }}/cache-tf-plugins

    - name: Pre-commit
      uses: open-turo/action-pre-commit@v3
      with:
        s3-bucket-name: ${{ inputs.s3-bucket-name }}
        s3-bucket-region: ${{ inputs.s3-bucket-region }}
      env:
        GODEBUG: asyncpreemptoff=1
    - name: Check release notes on pull_request
      if: github.event_name == 'pull_request'
      uses: open-turo/actions-release/lint-release-notes@v5
    - name: Post run
      if: always() && ${{ steps.create-credentials-file.outputs.terraform-cli-config-file-created }}
      shell: bash
      run: rm "$HOME/${{ inputs.terraform-cli-config-file }}" || true
