name: "terraform Lint"
description: "Lints terraform repository"
inputs:
  checkout-repo:
    required: false
    description: "Perform checkout as first step of action"
    default: true
  github-token:
    required: true
    description: "GitHub token that can create/delete comments. Usually - 'secrets.GITHUB_TOKEN'"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v4
      if: (github.actor!= 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/github_actions/') == false)
      with:
        configFile: .commitlintrc.yml
    - name: Run npm ci if needed
      if: hashFiles('package-lock.json') != ''
      shell: bash
      run: npm ci
    - uses: KeisukeYamashita/setup-release@v1.0.2
      with:
        repository: rhysd/actionlint
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
