name: "terraform Lint"
description: "Lints terraform repository"
inputs:
  checkout-repo:
    required: false
    description: "Perform checkout as first step of action"
    default: "true"
  github-token:
    required: true
    description: "GitHub Personal Access Token that can checkout the consumer git repository. e.g. 'secrets.GITHUB_TOKEN'"
  terraform-cli-credentials-token:
    required: true
    description: "The terraform cli config credentials token"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2
        cli_config_credentials_token: ${{ inputs.terraform-cli-credentials-token }}
    - uses: wagoid/commitlint-github-action@v4
      if: (github.actor!= 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/github_actions/') == false)
      with:
        configFile: .commitlintrc.yaml
    - uses: open-turo/action-pre-commit@v1
