name: "GitHub Action Release & Publish"
description: "Publish a new release of the Action - adds a new major tag"
inputs:
  checkout-repo:
    required: false
    description: "Perform checkout as first step of action"
    default: true
  dry-run:
    required: false
    description: "Whether to run semantic release in `dry-run` mode. It will override the dryRun attribute in your configuration file"
  extra-plugins:
    required: false
    description: "Extra plugins for pre-install. You can also specify specifying version range for the extra plugins if you prefer."
outputs:
  new_release_published:
    description: "Whether a new release was published"
    value: ${{ steps.release.outputs.new_release_published }}
  new_release_version:
    description: "Version of the new release"
    value: ${{ steps.release.outputs.new_release_version }}
  new_release_major_version:
    description: "Major version of the new release"
    value: ${{ steps.release.outputs.release-major }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - run: |
        echo "Release not implemented yet"
        exit 1
